# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ALMVVMReactiveSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ALMVVMReactiveSwift

pod 'SnapKit', '~> 4.0.0'
pod 'ReactiveCocoa', '~> 7.0.1'
pod 'Moya', '~> 10.0.1'
pod 'EVReflection', '~> 5.4.0'
pod 'IQKeyboardManagerSwift', '~> 5.0.7'
pod 'MBProgressHUD'

end
